src/objects/copado__Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Commit Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>copado__Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CopadoSnapShotCommitTriggerHandler.cls
/**
 * Trigger Handler to update Commit Status field from Snapshot Commit
 * Denormalization to allow Rollup Summary on User Story
**/
public with sharing class CopadoSnapShotCommitTriggerHandler {
    public static void handleUpdate(Map<Id,copado__Git_Org_Commit__c> updatedItems) {
       Set<Id> commits = updatedItems.keySet();
        
       System.debug('Commits Count: '+ commits.size());
       
       List<copado__User_Story_Commit__c> usCommits = new List<copado__User_Story_Commit__c>();
    
       for (copado__User_Story_Commit__c current : [SELECT Id, name
                                                        , Status__c
                                                        , copado__Snapshot_Commit__c
                                                     FROM copado__User_Story_Commit__c
                                                    WHERE copado__Snapshot_Commit__c IN :commits]) {
               current.status__c = updatedItems.get(current.copado__Snapshot_Commit__c).copado__Status__c ; 
               System.debug('CommitID: ' + current.name + ' status: ' + current.status__c);                                         
               usCommits.add(current);                                        
           }
       System.debug('US Commits Count:' + usCommits.size());
       update usCommits;
    }

}