src/objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Org__c.object
<CustomObject>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Released</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Design/Review of What&apos;s Built Meeting</fullName>
                </value>
                <value>
                    <fullName>Solution Review Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                    <label>Awaiting Component Review Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Recapture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Component Review Completed</fullName>
                </value>
                <value>
                    <fullName>Pending REM Review</fullName>
                </value>
                <value>
                    <fullName>REM Review Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserStoryListController_Test.cls
/**
   UserStoryListController_Test is a unit test for 
   UserStoryListController 
   which is used on the Apex Page: UserStoryListReview

   Author:  Bobby White
   Company:  Salesforce.com
   Date: April 13, 2017
**/
@isTest
private class UserStoryListController_Test {
	public static final String TYPE_APEXCLASS = 'ApexClass';
	public static final String TYPE_PROFILE = 'Profile';
	public static final String TYPE_CUSTOMOBJECT = 'CustomObject';
	public static final String TYPE_CUSTOMFIELD = 'CustomField';
	public static final String TYPE_RECORDTYPE = 'RecordType';
	public static final String TYPE_VALIDATIONRULE = 'ValidationRule';

	//public static final String STATUS_APPROVED = 'Approved';
	public static final String STATUS_DRAFT = 'Draft';

	@testSetup
	private static void setup() {
		TestDataFactory.setup();
		// Create extra local data we need for all of the tests
		copado__Project__c project = TestDataFactory.getProject();
		copado__Release__c release = TestDataFactory.getRelease(project.id);
		copado__Environment__c devSandbox = TestDataFactory.getEnvironment(project.Id);
        copado__Org__c orgCred = TestDataFactory.getDefaultOrgCred(devSandbox.id);


		// Create some User Stories
		List<copado__User_Story__c> stories = new List<copado__User_Story__c>();

        copado__User_Story__c userStory1 = new copado__User_Story__c (copado__User_Story_Title__c ='Sample1'
                                                                    ,copado__Project__c = project.id
                                                                    ,copado__Release__c = release.id
                                                                    ,copado__Org_Credential__c = orgCred.id
                                                                    ,copado__Environment__c = devSandbox.id
                                                                    ,copado__Status__c = STATUS_DRAFT);

         copado__User_Story__c userStory2 = new copado__User_Story__c (copado__User_Story_Title__c ='Sample2'
                                                                    ,copado__Project__c = project.id
                                                                    ,copado__Release__c = release.id
                                                                    ,copado__Org_Credential__c = orgCred.id
                                                                    ,copado__Environment__c = devSandbox.id
                                                                    ,copado__Status__c = STATUS_DRAFT);
 
        stories.add(userStory1);
        stories.add(userStory2);
        insert stories;

		// Add Commits
        TestDataFactory.addTestCommit(userStory1,createCommitSelections(1),'Test Commit1');
       	TestDataFactory.addTestCommit(userStory2,createCommitSelections(2),'Test Commit2');



	}


	
	@isTest static void test_NoneSelected() {

		UserStoryListController myListController = initController();

		List<CopadoMetadata> results =  myListController.getGitMetadataSelections();
		System.Assert(results!=null,'Never allowed to be null');
		System.AssertEquals(0,results.size(),'Expected to be empty');

		System.AssertEquals(null,myListController.init(),'Init expected to return null');
	}
	
	@isTest static void test_SomeSelected() {
		UserStoryListController myListController = initController();

		myListController.standardController.setSelected([SELECT Id, Name 
										From copado__User_Story__c
										Where copado__Status__c = :STATUS_DRAFT 
										LIMIT 10 ]);

		List<CopadoMetadata> results =  myListController.getGitMetadataSelections();

		// Test data inputs
		List<CopadoMetadata> testSelections = createCommitSelections(1);
		testSelections.addAll(createCommitSelections(2));

		System.Assert(results!=null,'Never allowed to be null');
		System.AssertEquals(Math.min(myListController.pageSize,testSelections.size()-1),results.size(),'Expected to be 1 overlap');
	}


	private static List<CopadoMetadata> createCommitSelections(Integer n) {

		List<CopadoMetadata> testSelections =  new List<CopadoMetadata>();

		if (n == 1) {
			testSelections.add(TestDataFactory.createSelection(TYPE_APEXCLASS,'MyTestClass'));
        	testSelections.add(TestDataFactory.createSelection(TYPE_APEXCLASS,'MyTestClass_Test'));
        	testSelections.add(TestDataFactory.createSelection(TYPE_PROFILE,'Admin'));
        	testSelections.add(TestDataFactory.createSelection(TYPE_CUSTOMOBJECT,'Opportunity'));
		} else {
			testSelections.add(TestDataFactory.createSelection(TYPE_APEXCLASS,'SecondClass'));
        	testSelections.add(TestDataFactory.createSelection(TYPE_APEXCLASS,'SecondClass_Test'));
        	testSelections.add(TestDataFactory.createSelection(TYPE_PROFILE,'Admin'));
        	testSelections.add(TestDataFactory.createSelection(TYPE_CUSTOMOBJECT,'Account'));			
		}

        return testSelections;
    }

	   /**
       Test helper method to simplify the common setup routines
    **/
	private static UserStoryListController initController() {
		// Create the Page and load the standard list controller
        Test.setCurrentPage(Page.UserStoryListReview);


        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(
        															[SELECT Id, Name 
																	  From copado__User_Story__c
																	 LIMIT 50 ]);
        
        UserStoryListController myListController = new UserStoryListController(stdSetController);

        return myListController;
	}

	
}