src/objects/copado__Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Commit Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>copado__Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UserStoryCommitTriggerHandler.cls
public without sharing class UserStoryCommitTriggerHandler {
    public static void handleBefore(List<copado__User_Story_Commit__c> usCommits) {
        Set<Id> commitIds = new Set<Id>();
        for (copado__User_Story_Commit__c current : usCommits) {
            commitIds.add(current.copado__Snapshot_Commit__c);
        }
        System.debug('commitIds.count: ' + commitIds.size());
        
        Map<Id,copado__Git_Org_Commit__c> snapShotCommits = new Map<Id,copado__Git_Org_Commit__c>(
                                                              [SELECT Id, copado__Status__c  
                                                              From copado__Git_Org_Commit__c 
                                                              Where Id IN :commitIds]);
        
        // Lookup against the map to find the status
        for (copado__User_Story_Commit__c current : usCommits ) {
            copado__Git_Org_Commit__c snapShotCommit = snapShotCommits.get(current.copado__Snapshot_Commit__c);
            current.Status__c = snapShotCommit.copado__Status__c;
            //current.Status__c = 'Pending';
            System.debug('Setting UserStory Commit.status=' + current.Status__c);
        }
    }

}