src/objects/copado__Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>ConflictCommits__c</fullName>
        <description>Commits with Conflicts</description>
        <label>Conflict Commits</label>
        <summaryFilterItems>
            <field>copado__User_Story_Commit__c.Status__c</field>
            <operation>equals</operation>
            <value>Conflict</value>
        </summaryFilterItems>
        <summaryForeignKey>copado__User_Story_Commit__c.copado__User_Story__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>copado__Promote_Change__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Promote Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Design/Review of What&apos;s Built Meeting</fullName>
                </value>
                <value>
                    <fullName>Solution Review Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                    <label>Awaiting Component Review Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Recapture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Component Review Completed</fullName>
                </value>
                <value>
                    <fullName>Pending REM Review</fullName>
                </value>
                <value>
                    <fullName>REM Review Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>copado__Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>copado__Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UserStoryValidation_Test.cls
/**
  UserStoryValidation_Test

  Acts as a FUNCTIONAL test to ensure end-to-end capability works as intended for User
  Story promotion.

  Author: Bobby White
  Date: March 23, 2017
  
**/
@isTest
public class UserStoryValidation_Test {

	@testSetup
	private static void setup() {
		TestDataFactory.setup();
	}

	/**
	  Scenario - no conflict commits, ensure that the validation rules don't prevent
	  the user story from being flagged for promotion
	**/
	private static testmethod void testPositive() {
        // Update Commit status from Pending --> Complete
        // Add Commit As Pending
        // Add UserStory Commit
        // Update the original Commit to 'Complete'
        copado__User_Story__c theUserStory = TestDataFactory.getUserStory();
        
        copado__Git_Org_Commit__c theTestCommit = TestDataFactory.getSnapShotCommit();
        copado__User_Story_Commit__c  usCommit = new copado__User_Story_Commit__c (copado__Snapshot_Commit__c = theTestCommit.id
                                                                                  ,copado__User_Story__c = theUserStory.id);
        insert usCommit;
        
        System.debug('Commit.id: ' + usCommit.Id);
        
        theTestCommit.copado__Status__c = TestDataFactory.COMPLETE;
        update theTestCommit;
        
        Test.startTest();

        theUserStory = [SELECT Id, ConflictCommits__c 
                          FROM copado__User_Story__c
                         WHERE id = :theUserStory.id];

        // Now attempt to set the user story to promote and save it
        System.Assert(theUserStory.ConflictCommits__c == 0,'Did not expect conflict commits');
        theUserStory.copado__Promote_Change__c = true;
        update theUserStory;

        System.Assert(true,'Success');

        Test.stopTest();
               
        
      
	}

	/**
	  Scenario - Story has conflict commits, ensure that the validation rules prevent
	  the user story from being flagged for promotion
	**/
	private static testmethod void testConflict() {
		 // Update Commit status from Pending --> Complete
        // Add Commit As Pending
        // Add UserStory Commit
        // Update the original Commit to 'Conflict'

        copado__User_Story__c theUserStory = TestDataFactory.getUserStory();
        
        copado__Git_Org_Commit__c theTestCommit = TestDataFactory.getSnapShotCommit();
        copado__User_Story_Commit__c  usCommit = new copado__User_Story_Commit__c (copado__Snapshot_Commit__c = theTestCommit.id
                                                                                  ,copado__User_Story__c = theUserStory.id);
        insert usCommit;
        
        System.debug('Commit.id: ' + usCommit.Id);
        
        theTestCommit.copado__Status__c = TestDataFactory.CONFLICT;
        update theTestCommit;
        
        Test.startTest();

        theUserStory = [SELECT Id, ConflictCommits__c 
                          FROM copado__User_Story__c
                         WHERE id = :theUserStory.id];

        System.Assert(theUserStory.ConflictCommits__c == 1,'Expected conflict commits');


        // Now attempt to set the user story to promote and save it
        try {
        	theUserStory.copado__Promote_Change__c = true;
            update theUserStory;
            System.Assert(false,'Failed to raise expected validation error');

        } catch (System.DmlException ex) {
            System.Assert(ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'),'Expected a validation error mentioning conflicts');
        }



        Test.stopTest();
               
        
      


	}
}