src/objects/copado__Deployment__c.object
<CustomObject>
    <fields>
        <fullName>copado__From_Org__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Deployments (From Org)</relationshipLabel>
        <relationshipName>Deployments_From_Org</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Destination_Org__c.object
<CustomObject>
    <fields>
        <fullName>copado__Deployment__c</fullName>
        <label>Deployment</label>
        <referenceTo>copado__Deployment__c</referenceTo>
        <relationshipLabel>Destination Orgs</relationshipLabel>
        <relationshipName>Destination_Orgs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>Completed with Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__To_Org__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>To Org</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.CreatedById</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Deployments To</relationshipLabel>
        <relationshipName>Deployments_to</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Destination Org</label>
    <nameField>
        <displayFormat>DO-{0000}</displayFormat>
        <label>Destination Org Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destination Orgs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Org__c.object
<CustomObject>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DestinationOrgTriggerHandler_Test.cls
/**
  Class:   DestinationOrgTriggerHandler_Test

  Author:  Bobby White
  Company:  Salesforce.com
**/
@isTest
private class DestinationOrgTriggerHandler_Test {

    @testSetup static void setup() {
        // Create the Deployment Flow, etc
        TestDataFactory.setup();

        // Create Deployment
        copado__Org__c devOrg = getOrgByName(TestDataFactory.ORGNAME_DEV);
        copado__Org__c sitOrg = getOrgByName(TestDataFactory.ORGNAME_SIT);
        copado__Org__c prodOrg = getOrgByName(TestDataFactory.ORGNAME_PROD);

        copado__Deployment__c deployment = new copado__Deployment__c(name='Test Deployment', copado__From_Org__c = devOrg.id);
        insert deployment;

        List<copado__Destination_Org__c> destinations = new List<copado__Destination_Org__c>();

        destinations.add(new copado__Destination_Org__c(copado__Deployment__c=deployment.id, copado__To_Org__c=sitOrg.id));
        destinations.add(new copado__Destination_Org__c(copado__Deployment__c=deployment.id, copado__To_Org__c=prodOrg.id));

        insert destinations;

    }
    
    @isTest static void test_noPerms() {
        Test.startTest();

        Database.SaveResult[] results = updateDestinationOrgs();

        Test.stopTest();

        System.Assert(checkResults(results,Label.MSG_NO_BMGT_PERMISSIONS),'Expected FAILURE');

    }
    
    @isTest static void test_withPerms() {

        addBranchManagementPerms();

        Test.startTest();

        Database.SaveResult[] results = updateDestinationOrgs();

        Test.stopTest();

        System.Assert(checkResults(results,null),'Expected Success');


    }

    private static copado__Org__c getOrgByName(String name) {
        List<copado__Org__c> orgs = [SELECT id, name From copado__Org__c Where name = :name LIMIT 1];
        return orgs.isEmpty() ? null : orgs[0];
    }

    private static copado__Deployment__c getDeployment() {
         return [SELECT id,name From copado__Deployment__c LIMIT 1];
    }

    private static Database.SaveResult[] updateDestinationOrgs() {
        // Update all of the Destinations for our deployment do it in bulk
        copado__Deployment__c myDeployment = getDeployment();
        List<copado__Destination_Org__c> destinations = [SELECT id
                                                              , copado__Status__c
                                                              , copado__To_Org__c 
                                                           From copado__Destination_Org__c
                                                           Where copado__Deployment__c = :myDeployment.id];
        for (copado__Destination_Org__c current : destinations) {
            current.copado__Status__c = 'In Progress';
        }

        // Execute using Database method to allow partial success in Bulk mode
        return Database.update(destinations, false);
    }

    private static Boolean checkResults(Database.SaveResult[] results, String expectedMsg) {
        for (Database.SaveResult result : results) {
            if (expectedMsg != null && result.getErrors().isEmpty()) {
                return false;
            } else if (expectedMsg != null && !result.getErrors().isEmpty()) {
                System.Assert(result.getErrors()[0].getMessage().contains(expectedMsg),'Expected message not found');
            } else if (expectedMsg == null && !result.getErrors().isEmpty()) {
                System.AssertEquals(null,result.getErrors()[0].getMessage(),'No message expected');
            }
        }

        return true;
    }

    private static void addBranchManagementPerms() {

        List<copado__Branch_Management_Permission__c> bPerms = new List<copado__Branch_Management_Permission__c>();

        for (copado__Environment__c current : [SELECT Id, Name 
                                                    From copado__Environment__c 
                                                   LIMIT 100] ) {
            bPerms.add(new copado__Branch_Management_Permission__c(copado__Environment__c=current.Id
                                                                , copado__Allow_Deployments__c=true
                                                                , copado__User__c = userInfo.getUserId()));
        }

        insert bPerms;

    }
    
}