src/objects/copado__Environment__c.object
<CustomObject>
    <fields>
        <fullName>IsDevelopmentSandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Development Sandbox?</description>
        <inlineHelpText>Development Sandboxes are used to develop new features and fix bugs.  Non development Sandboxes are not allowed to Commit changes to Copado.</inlineHelpText>
        <label>Is Development Sandbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsManaged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a managed Sandbox?</description>
        <inlineHelpText>Managed Sandboxes are operated by the Release Engineering Team.  Project teams don&apos;t have rights to promote here.</inlineHelpText>
        <label>Is Managed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Production/Developer</fullName>
                </value>
                <value>
                    <fullName>Sandbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Org__c.object
<CustomObject>
    <fields>
        <fullName>IsDevelopmentSandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this Org Credential associated with a Development Sandbox?</description>
        <label>IsDevelopmentSandbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsManaged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a Managed Org?</description>
        <inlineHelpText>Managed orgs are under strict controls managed by the Release Engineering team.  Unmanaged orgs are generally accessible to all project teams.</inlineHelpText>
        <label>IsManaged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EnvironmentTriggerHandler.cls
/**
   Copado Environment Trigger Handler class

   Does the heavy lifting for the trigger

   Must run without sharing to ensure that operations will succeed regardless of visibility provided through sharing rules
**/
public without sharing class EnvironmentTriggerHandler {
	public static final String TYPE_SANDBOX = 'Sandbox';
     /**
       Set default values - Production Orgs are always managed
     **/
	 public static void handleBeforeInsert(List<Copado__Environment__c> environments) {

	 	System.debug('handleBeforeInsert');

	 	for (Copado__Environment__c current : environments) {
	 		current.isManaged__c = (current.copado__Type__c != TYPE_SANDBOX);
	 		System.debug('Name: ' + current.name + ' Type: ' + current.copado__type__c + ' isManaged: ' + current.isManaged__c);
	 	}


	 }

	 /**
	    Handle After Insert operation
	 **/
	 public static void handleAfterInsert(Map<Id,Copado__Environment__c> envMap) {
	 	setOrgCredentialFields(envMap);
	 }

	 /**
	 **/
	 public static void handleAfterUpdate(Map<Id,Copado__Environment__c> envMap) {
	 	setOrgCredentialFields(envMap);
	 }

	 /**
	    Set isManaged and isDevelopmentSandbox fields on Org Credentials tied to Environment
	 **/
	 private static void setOrgCredentialFields(Map<Id,Copado__Environment__c> envMap)  {
	 	// Query for the Org Credentials Connected to these Environments
	 	// Propagate the values of isManaged and isDevelopmentSandbox


        final List<copado__Org__c> orgCreds = new List<copado__Org__c>();
	 	for (copado__Org__c current : [SELECT id, copado__Environment__c 
	 		                             FROM copado__Org__c
	 		                            WHERE copado__environment__c IN :envMap.keySet()]) {
	 		Copado__Environment__c env = envMap.get(current.Copado__Environment__c);
	 		current.isManaged__c = env.isManaged__c;
	 		current.isDevelopmentSandbox__c = env.isDevelopmentSandbox__c;
	 		orgCreds.add(current);
	 	}

	 	if (!orgCreds.isEmpty()) {
	 		update orgCreds;
	 	}
	 }
}