src/objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Org__c.object
<CustomObject>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__Promotion__c.object
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions (Destination Environment)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Destination_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The credential to the Destination Environment that should be used when creating a deployment. This may be auto-populated, if left blank, based on the project&apos;s deployment flow if you are the owner of an Org Credential to the Destination Environment.</inlineHelpText>
        <label>Destination Org Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Destination_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Destination Org Credential)</relationshipLabel>
        <relationshipName>Promotions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will provide the ability to deploy User Stories within a Release.</description>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The credential to the Source Environment that should be used when creating a deployment. This may be auto-populated, if left blank, based on the project&apos;s deployment flow if you are the owner of an Org Credential to the Source Environment.</inlineHelpText>
        <label>Source Org Credential</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>copado__Org__c.copado__Environment__c</field>
                <operation>equals</operation>
                <valueField>$Source.copado__Source_Environment__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>Promotions (Source Org Credential)</relationshipLabel>
        <relationshipName>Promotions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__Release__c.object
<CustomObject>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>copado__Release__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Promotion_CC_Test.cls
@isTest
private class Promotion_CC_Test {
	public static final String TYPE_APEXCLASS = 'ApexClass';
	public static final String TYPE_PROFILE = 'Profile';
	public static final String TYPE_CUSTOMOBJECT = 'CustomObject';
	public static final String TYPE_CUSTOMFIELD = 'CustomField';
	public static final String TYPE_RECORDTYPE = 'RecordType';
	public static final String TYPE_VALIDATIONRULE = 'ValidationRule';
	
	@testSetup
	private static void setup() {
		TestDataFactory.setup();
		// Create extra local data we need for all of the tests
		copado__Project__c project = TestDataFactory.getProject();
		copado__Release__c release = TestDataFactory.getRelease(project.id);
		copado__Environment__c devSandbox = TestDataFactory.getEnvironment(project.Id);
        copado__Org__c orgCred = TestDataFactory.getDefaultOrgCred(devSandbox.id);


		// Create a User Story
        copado__User_Story__c userStory1 = new copado__User_Story__c (copado__User_Story_Title__c ='Sample1'
                                                                    ,copado__Project__c = project.id
                                                                    ,copado__Release__c = release.id
                                                                    ,copado__Org_Credential__c = orgCred.id
                                                                    ,copado__Environment__c = devSandbox.id);
        insert userStory1;

		// Add Commits
        TestDataFactory.addTestCommit(userStory1,createCommitSelections(),'Test Commit');

		// Add them to a Promotion
		copado__Promotion__c myPromotion = new copado__Promotion__c(copado__release__c = release.id
																   ,copado__Source_Environment__c = devSandbox.id
																   ,copado__Source_Org_Credential__c = orgCred.id
																   ,copado__Destination_Environment__c = devSandbox.id  //FIXME
																   ,copado__Destination_Org_Credential__c = orgCred.id  //FIXME
																   );
		insert myPromotion;

		copado__Promoted_User_Story__c promoUserStory = new copado__Promoted_User_Story__c();
		promoUserStory.copado__Promotion__c = myPromotion.id;
		promoUserStory.copado__User_Story__c = userStory1.id;
		insert promoUserStory;
	}

	@isTest static void test_getRecordName() {
		copado__promotion__c myPromotion = getPromotion();
		Promotion_CC myCustomController =  initController(myPromotion);
		System.AssertEquals(myCustomController.getRecordName(),myPromotion.name,'must equal');
	}
	
	@isTest static void test_getSelections() {

		copado__promotion__c myPromotion = getPromotion();
		Promotion_CC myCustomController =  initController(myPromotion);
		System.AssertEquals(myCustomController.getRecordName(),myPromotion.name,'must equal');

		List<CopadoMetadata> testSelections = createCommitSelections();

		Test.startTest();

        List<CopadoMetadata> selections = myCustomController.getGitMetadataSelections();

        System.Assert(selections!=null,'Even if no commits, this list must not be null');
        System.AssertEquals(selections.size(),testSelections.size(),'Expected same number of items');

        Test.stopTest();
	}

	@isTest static void test_NoChangeCommit() {

		copado__promotion__c myPromotion = getPromotion();

		copado__User_Story__c userStory1 = [SELECT id, name, copado__Org_Credential__c
		                                      FROM copado__User_Story__c 
		                                     WHERE id IN (SELECT copado__User_Story__c 
		                                                    FROM copado__Promoted_User_Story__c 
		                                                   WHERE copado__Promotion__c = :myPromotion.id) LIMIT 1];

		// Add an Empty Commit
        TestDataFactory.addTestCommit(userStory1,new List<CopadoMetaData>(),'No Change Commit');


		Promotion_CC myCustomController =  initController(myPromotion);
		System.AssertEquals(myCustomController.getRecordName(),myPromotion.name,'must equal');

		List<CopadoMetadata> testSelections = createCommitSelections();

		Test.startTest();

        List<CopadoMetadata> selections = myCustomController.getGitMetadataSelections();

        System.Assert(selections!=null,'Even if no commits, this list must not be null');
        System.AssertEquals(selections.size(),testSelections.size(),'Expected same number of items');

        Test.stopTest();
	}


	// Retreive our test promotion
	private static copado__Promotion__c getPromotion() {
         return [SELECT id, name from copado__Promotion__c LIMIT 1];
	}

    private static List<CopadoMetadata> createCommitSelections() {

		List<CopadoMetadata> testSelections =  new List<CopadoMetadata>();

        testSelections.add(TestDataFactory.createSelection(TYPE_APEXCLASS,'MyTestClass'));
        testSelections.add(TestDataFactory.createSelection(TYPE_APEXCLASS,'MyTestClass_Test'));
        testSelections.add(TestDataFactory.createSelection(TYPE_PROFILE,'Admin'));
        testSelections.add(TestDataFactory.createSelection(TYPE_CUSTOMOBJECT,'Opportunity'));

        return testSelections;
    }

	   /**
       Test helper method to simplify the common setup routines
    **/
	private static Promotion_CC initController(copado__Promotion__c thePromotion) {
		// Create the Page and load the standard controller
        Test.setCurrentPage(Page.PromotionReview);
        ApexPages.currentPage().getParameters().put('id',thePromotion.id);

        return new Promotion_CC();
	}
	
}