src/objects/copado__Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Design/Review of What&apos;s Built Meeting</fullName>
                </value>
                <value>
                    <fullName>Solution Review Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                    <label>Awaiting Component Review Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Recapture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Component Review Completed</fullName>
                </value>
                <value>
                    <fullName>Pending REM Review</fullName>
                </value>
                <value>
                    <fullName>REM Review Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>copado__Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>copado__Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UserStoryCommitUtil.cls
public with sharing class UserStoryCommitUtil {

    public static List<CopadoMetadata> getGitMetadataSelections(List<Id> usList) {
	        // Get all of the Snapshot Commits for these User Stories
        List<CopadoMetadata> allCommitSelections = new List<CopadoMetadata>();
        List<Id> commitIds = new List<Id>();
        Map<Id,String> userStoryNames = new Map<Id,String>();

        // we must grab the Commit Ids first because the Attachments are nested there
        for (copado__user_story_commit__c current : [SELECT Id, name, copado__User_Story__c
        												                          , copado__User_Story__r.name
        												                          , copado__Snapshot_Commit__c
                                                       FROM copado__user_story_commit__c
                                                      WHERE copado__User_Story__c IN :usList
                                                        AND copado__Snapshot_Commit__r.copado__status__c = 'Complete'
                                                      ORDER BY copado__User_Story__r.name]) {

          // Save the name of the UserStory so we can lookup while getting the attachment bodies
          Id commitId = current.copado__Snapshot_Commit__c;
          commitIds.add(commitId);
          userStoryNames.put(commitId,current.copado__User_Story__r.name);
          System.Debug('UserStory:' + current.copado__User_Story__r.name);


        	
        }

        System.debug('Count of Commits: ' + commitIds.size());
        
        // Bulkified Query for the Attachment Bodies
        for (Attachment current : [SELECT Id, Name, ParentId, Body 
                                               FROM Attachment
                                              WHERE Name = 'MetaData'
                                                and ParentId IN :commitIds]) {


            List<CopadoMetadata> commitSelections = CopadoMetadata.parseArray(current.Body.toString());
            for (CopadoMetadata currentSel : commitSelections) {
                    // Save the name of the UserStory so we can cross reference
                  currentSel.userStoryReferences = userStoryNames.get(current.ParentId);
            }
            allCommitSelections.addAll(commitSelections); // this is unordered, not unique

        }

        System.Debug('Count of Selections: ' + allCommitSelections.size());

        // Eliminate duplicates
        Map<String,CopadoMetadata> selectionsMap = new Map<String,CopadoMetadata>();
        for (CopadoMetadata current : allCommitSelections) {
            if (!selectionsMap.containsKey(current.getKey())) {
                selectionsMap.put(current.getKey(),current);
            } else {
            	CopadoMetadata existing = selectionsMap.get(current.getKey());
            	existing.userStoryReferences += ',' + current.userStoryReferences;
            }
        }

        List<CopadoMetadata> dedupedSelections = selectionsMap.values();

        dedupedSelections.sort();

        // Dedupe the references
        for (CopadoMetadata current : dedupedSelections) {
        	current.dedupReferences();
        }
        return dedupedSelections;

    }

}