src/objects/copado__Deployment_Flow__c.object
<CustomObject>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment Flow</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Promote_and_Deploy__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this checkbox is checked, a promotion and deployment of this User Story will be started.</inlineHelpText>
        <label>Promote and Deploy</label>
        <type>Checkbox</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserStoryTriggerHandler.cls
/**
	User Story Trigger for Copado Managed Package

	Author: Bobby White
	Company: Salesforce.com
	Date: June 24, 2017
**/
public with sharing class UserStoryTriggerHandler {
	/**
	  Validations that require Apex code + default overrides
	**/
	public static void handleBeforeInsert() {
		for (copado__User_Story__c current : (List<copado__User_Story__c>) Trigger.new) {
			current.copado__Promote_and_Deploy__c = false; // clear this if cloned record or bulk load
		}
	}

	/**
	  Validations that require Apex code
	**/	
	public static void handleBeforeUpdate() {

		System.Debug('handleBeforeUpdate');
		List<Id> mentions = new List<Id>();
		mentions.add(UserInfo.getUserId());


		//List<copado__User_Story__c> toValidateBMP = new List<copado__User_Story__c>();

		for (copado__User_Story__c current : (List<copado__User_Story__c>) Trigger.new) {

			if (current.copado__Promote_and_Deploy__c) {
				if (current.copado__Project__c == null || current.copado__Environment__c == null) {
					current.addError(Label.MSG_PROMOTE_REQUIRED_FIELDS);
				} else {
					// Need to validate that they have Branch Management Permissions to execute deployment in destination
					// destination is configured in the Deployment flow associated with this Project.
					// ProjectId + SourceEnvId
					//toValidateBMP.add(current);
					if (!hasBMPForDestination(current)) {

						// Instead of throwing an error, we're just going to turn it back off!
						current.copado__Promote_and_Deploy__c = false;
					}
				}
			}
		}

	}

	@TestVisible private static Boolean hasBMPForDestination(copado__User_Story__c current) {
		final copado__Project__c project = [SELECT id, copado__Deployment_Flow__c 
											  FROM copado__Project__c 
									   		 Where Id = :current.copado__Project__c];

		final List<copado__Deployment_Flow_Step__c> steps = [SELECT copado__Destination_Environment__c 
												  		 	   FROM copado__Deployment_Flow_Step__c 
												 			  WHERE copado__Deployment_Flow__c = :project.copado__Deployment_Flow__c
												   		  		AND copado__Source_Environment__c = :current.copado__Environment__c];

		if (steps.isEmpty()) {
			System.Debug('No deployment steps found');
			return false; 
		}

		final List<copado__Branch_Management_Permission__c> bmps = [SELECT copado__Allow_Deployments__c, copado__Environment__r.name
		   												 	    	  FROM copado__Branch_Management_Permission__c
		  													   		 WHERE copado__User__c = : userInfo.getUserId() 
		    											  	     	   AND copado__Environment__c = : steps[0].copado__Destination_Environment__c];

		System.Debug('No BMP - isEmpty?' + bmps.IsEmpty() + ' count=' + bmps.size());
		
		Boolean hasBMP = bmps.isEmpty() ? false : bmps[0].copado__Allow_Deployments__c;
		if (!hasBMP) {
			final List<Id> mentions = new List<Id>();
			mentions.add(UserInfo.getUserId());
			final String envName =  (bmps.isEmpty() ? (String) steps[0].copado__Destination_Environment__c : bmps[0].copado__Environment__r.name);
			final String msg = Label.MSG_NO_BMGT_PERMISSIONS + ' ' + envName;
			System.debug('BMP env=' + envName);
			NotifyUtil.sendEmail('User Story ' + current.name + ' cannot Promote & Deploy',msg);
			NotifyUtil.chatterPost(current.id,' ' + msg,mentions);
		}

		return hasBMP;
	}
}