src/objects/copado__Deployment_Flow__c.object
<CustomObject>
    <label>Deployment Flow</label>
    <nameField>
        <label>Deployment Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__Deployment_Flow_Step__c.object
<CustomObject>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <label>Deployment Flow</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__Destination_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Destination Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps (Destination Environment)</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Source_Environment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Source Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Deployment Flow Steps</relationshipLabel>
        <relationshipName>Deployment_Flow_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deployment Flow Step</label>
    <nameField>
        <displayFormat>DFS-{000000}</displayFormat>
        <label>Deployment Flow Step Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Flow Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__Environment__c.object
<CustomObject>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Org__c.object
<CustomObject>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>Org Credentials</relationshipLabel>
        <relationshipName>Org_Credentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Credential</label>
    <nameField>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/copado__Project__c.object
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <fields>
        <fullName>copado__Deployment_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deployment Flow</label>
        <referenceTo>copado__Deployment_Flow__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Environment</label>
        <referenceTo>copado__Environment__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Org_Credential__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Org Credential</label>
        <referenceTo>copado__Org__c</referenceTo>
        <relationshipLabel>User Stories (Org Credential)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>copado__Project__c</referenceTo>
        <relationshipLabel>User Stories</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>copado__Promote_and_Deploy__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When this checkbox is checked, a promotion and deployment of this User Story will be started.</inlineHelpText>
        <label>Promote and Deploy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>copado__User_Story_Title__c</fullName>
        <label>User Story Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <recordTypes>
        <fullName>Active</fullName>
        <active>true</active>
        <description>Active User Story Record Type</description>
        <label>Active</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserStoryTriggerHandler_Test.cls
@isTest
private class UserStoryTriggerHandler_Test {

	
	@isTest static void test_Insert() {

		TestDataFactory.setup();

		// Create a user Story setting Promote & Deploy
		copado__User_Story__c myUserStory = new copado__User_Story__c();
		myUserStory.copado__User_Story_Title__c = 'Test';
		myUserStory.copado__project__c = TestDataFactory.getProject().id;
		myUserStory.copado__promote_and_deploy__c = true;

		insert myUserStory;

		copado__User_Story__c afterInsert = [SELECT id,copado__promote_and_deploy__c From copado__User_Story__c where Id = :myUserStory.id];

		System.AssertEquals(false,afterInsert.copado__promote_and_deploy__c,'Expected promote and deploy to be off');


	}

	@isTest static void test_UpdateMissingReqFields() {

		TestDataFactory.setup();

		copado__User_Story__c myUserStory = TestDataFactory.getUserStory();
		myUserStory.copado__promote_and_deploy__c = true;
		myUserStory.copado__project__c = null; // null this out

		try {

			update myUserStory;
			System.Assert(false,'Should not reach this line');

		} catch (System.DmlException ex) {
			System.Assert(ex.getMessage().contains(Label.MSG_PROMOTE_REQUIRED_FIELDS),'Expected required fields validation error');
		}
	}
	
	@isTest static void test_UpdateNoBMP() {

		TestDataFactory.setup();

		copado__User_Story__c myUserStory = TestDataFactory.getUserStory();
		myUserStory.copado__promote_and_deploy__c = true;

		update myUserStory;

		copado__User_Story__c afterUpdate = [SELECT id,copado__promote_and_deploy__c From copado__User_Story__c where Id = :myUserStory.id];

		System.AssertEquals(false,afterUpdate.copado__promote_and_deploy__c,'Expected promote and deploy to be off');		
	}

    /**
      SPECIAL Handling here... can't create the Deployment Flow steps because of this exception:
       MESSAGE 
System.DmlException: Insert failed. First exception on row 0; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, The maximum number of active connections has already been reached. 
Please deactivate some Deployment Flows or contact Sales@copa.do to increase your limit.: []

Until we get a workaround for this, we have to enable SeeAllData=true :-(
    **/
	@isTest(seeAllData=true) 
	static void test_UpdateYesBMP() {

		// Pick an existing Deployment Flow Step
		copado__deployment_flow_step__c step = [SELECT id
													 , copado__Deployment_Flow__c
													 , copado__Source_Environment__c
													 , copado__Destination_Environment__c
												  FROM copado__deployment_flow_step__c
												  LIMIT 1];

		// Pick an existing Project that references this Flow
		copado__Project__c project = [SELECT Id 
										From copado__Project__c 
									   Where copado__deployment_flow__c = :step.copado__deployment_flow__c LIMIT 1];

		copado__Org__c orgCred = [SELECT id From copado__Org__c 
								   Where copado__environment__c = :step.copado__Source_Environment__c
								   	LIMIT 1];

		copado__User_Story__c myUserStory = new copado__User_Story__c(copado__project__c = project.id
																	 ,copado__environment__c = step.copado__Source_Environment__c
																	 ,copado__Org_Credential__c = orgCred.id);

		insert myUserStory;


		Test.startTest();

		User testUser = TestDataFactory.getDevUser();

		System.RunAs(testUser) {
				myUserStory.copado__promote_and_deploy__c = true;
				final Boolean result = UserStoryTriggerHandler.hasBMPForDestination(myUserStory);
				System.AssertEquals(false,result,'Expected BMP to be false before adding');		

		}


		// Add BMP for the destination Environment
		copado__Branch_Management_Permission__c bmp = new copado__Branch_Management_Permission__c(copado__environment__c=step.copado__Destination_Environment__c
																								 ,copado__Allow_Deployments__c = true
																								 ,copado__User__c = testUser.id);
		insert bmp;


		System.RunAs(testUser) {
				myUserStory.copado__promote_and_deploy__c = true;
				final Boolean result = UserStoryTriggerHandler.hasBMPForDestination(myUserStory);
				System.AssertEquals(true,result,'Expected BMP to be yes');		

		}

		Test.stopTest();

	}
	
}