src/objects/copado__Git_Org_Commit__c.object
<CustomObject>
    <description>This object stores the individual commits to a Git repository executed by Copado Deployer.</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Snapshot Commit</label>
    <nameField>
        <displayFormat>Cmt-{0000}</displayFormat>
        <label>Commit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snapshot Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/copado__User_Story__c.object
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <fields>
        <fullName>copado__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Design/Review of What&apos;s Built Meeting</fullName>
                </value>
                <value>
                    <fullName>Solution Review Completed</fullName>
                </value>
                <value>
                    <fullName>Awaiting Approval</fullName>
                    <label>Awaiting Component Review Approval</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Ready for testing</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Recapture</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Component Review Completed</fullName>
                </value>
                <value>
                    <fullName>Pending REM Review</fullName>
                </value>
                <value>
                    <fullName>REM Review Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/copado__User_Story_Commit__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Commit Status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>No changes</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Conflict</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>copado__Snapshot_Commit__c</fullName>
        <label>Snapshot Commit</label>
        <referenceTo>copado__Git_Org_Commit__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>copado__User_Story__c</fullName>
        <label>User Story</label>
        <referenceTo>copado__User_Story__c</referenceTo>
        <relationshipLabel>User Story Commits</relationshipLabel>
        <relationshipName>User_Story_Commits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>User Story Commit</label>
    <nameField>
        <label>US Commit</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Story Commits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CopadoSnapShotCommitTriggerHandler_Test.cls
/**
 * Test the CopadoSnapShotCommitTriggerHandler class
 **/
@istest
public class CopadoSnapShotCommitTriggerHandler_Test {
        
    @testSetup public static void setup() {
        TestDataFactory.setup();
    }

        
    /**
     * User Story adds a Commit as Pending
     **/ 
    private static testmethod void testInsert() {
        // Add Commit As Pending
        // Add UserStory Commit
         
        copado__User_Story_Commit__c  usCommit = new copado__User_Story_Commit__c (copado__Snapshot_Commit__c = TestDataFactory.getSnapShotCommit().id
                                                                                  ,copado__User_Story__c = TestDataFactory.getUserStory().id);
        insert usCommit;
        
        
        
        System.debug('Commit.id: ' + usCommit.Id);
        
        Test.startTest();
        copado__User_Story_Commit__c usCommitAfter = [SELECT id,name,Status__c 
                                                      FROM copado__User_Story_Commit__c
                                                      WHERE id = :usCommit.id];
        Test.stopTest();
        
        System.Assert(usCommitAfter != null,'After must not be null');
        System.AssertEquals(usCommitAfter.status__c,TestDataFactory.PENDING,'Expected Pending Status');
        
    }
 
    private static testmethod void testUpdate() {
        // Update Commit status from Pending --> Complete
        // Add Commit As Pending
        // Add UserStory Commit
        // Update the original Commit to 'Complete'
        
        copado__Git_Org_Commit__c theTestCommit = TestDataFactory.getSnapShotCommit();
        copado__User_Story_Commit__c  usCommit = new copado__User_Story_Commit__c (copado__Snapshot_Commit__c = theTestCommit.id
                                                                                  ,copado__User_Story__c = TestDataFactory.getUserStory().id);
        insert usCommit;
        
        System.debug('Commit.id: ' + usCommit.Id);
        
        theTestCommit.copado__Status__c = TestDataFactory.COMPLETE;
        update theTestCommit;
        
        Test.startTest();
        copado__User_Story_Commit__c usCommitAfter = [SELECT id,name,Status__c 
                                                      FROM copado__User_Story_Commit__c
                                                      WHERE id = :usCommit.id];
        Test.stopTest();
        
        System.Assert(usCommitAfter != null,'After must not be null');
        System.AssertEquals(usCommitAfter.status__c,TestDataFactory.COMPLETE,'Expected Complete Status');
        
        
        
    }

}